spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
server.port=10000

#Ambientes de prueba
#spring.datasource.url=jdbc:mysql://localhost:3306/portfoliobackend?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=

#Ambiente de produccion
spring.datasource.url=jdbc:mysql://bukdc3qmgn2e10tjtcm6-mysql.services.clever-cloud.com:3306/bukdc3qmgn2e10tjtcm6?useSSL=false&serverTimezone=UTC
spring.datasource.username=uvskoqtbgtxwn1ja
spring.datasource.password=9GtnLetqYdbwdxYpA64m

#JWT
jwt.secret=secret
jwt.expiration=3600